/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Event Management API
 * API for Event Management System
 * OpenAPI spec version: 1.0.0
 */

export type EventListItemVisibility = typeof EventListItemVisibility[keyof typeof EventListItemVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventListItemVisibility = {
  public: 'public',
  private: 'private',
} as const;
