/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Event Management API
 * API for Event Management System
 * OpenAPI spec version: 1.0.0
 */

export type ListEventsStatus = typeof ListEventsStatus[keyof typeof ListEventsStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListEventsStatus = {
  draft: 'draft',
  published: 'published',
  closed: 'closed',
  archived: 'archived',
} as const;
