/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Event Management API
 * API for Event Management System
 * OpenAPI spec version: 1.0.0
 */

export type ListEventsSortBy = typeof ListEventsSortBy[keyof typeof ListEventsSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListEventsSortBy = {
  date: 'date',
  name: 'name',
  status: 'status',
} as const;
